# Generated by Django 5.1 on 2024-08-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_seats', models.IntegerField(default=0)),
                ('level', models.IntegerField(choices=[(1, 'class A'), (2, 'class B')], default=1)),
                ('has_ac', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.IntegerField(choices=[(0, 'DAMASCUS'), (1, 'ALEPPO'), (2, 'HOMS'), (3, 'LATAKIA'), (4, 'TARTOUS'), (5, 'HAMAH')], default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('journey_type', models.IntegerField(choices=[(1, 'metro'), (2, 'domestic'), (3, 'international')], default=1)),
                ('cart_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('first_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform1', to='base.platform')),
                ('second_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform2', to='base.platform')),
            ],
        ),
        migrations.CreateModel(
            name='JourneyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('has_stop_in_arrival', models.BooleanField(default=False)),
                ('route_order', models.PositiveSmallIntegerField(default=0)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.journey')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.route')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.train')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='route',
            field=models.ManyToManyField(through='base.JourneyRoute', to='base.route'),
        ),
        migrations.AddField(
            model_name='platform',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.station'),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.IntegerField(choices=[(1, 'metro'), (2, 'domestic'), (3, 'international')], default=-1)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arr', to='base.platform')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep', to='base.platform')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='time_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.timetable'),
        ),
        migrations.CreateModel(
            name='CartTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=-1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cart')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.train')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='train',
            field=models.ManyToManyField(through='base.CartTrain', to='base.train'),
        ),
    ]
